### ISSUE TITLE
Bug when starting up for first time. Topic missing?

### ISSUE THREAD

**Issue by TopSwagCode** [gabrielsadaka/dotnet-kafka-sample#20]
`consumer_1   | info: ConsumerWorker.Worker[0]
consumer_1   |       Worker running at: 10/30/2020 22:56:27 +00:00
consumer_1   | %3|1604098587.211|ERROR|rdkafka#consumer-2| [thrd:GroupCoordinator]: 1/1 brokers are down
consumer_1   | Unhandled exception. Confluent.Kafka.ConsumeException: Broker: Unknown topic or partition
consumer_1   |    at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
consumer_1   |    at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
consumer_1   |    at Common.Kafka.Consumer.KafkaTopicMessageConsumer.StartConsuming(String topic, CancellationToken cancellationToken) in /source/src/Common.Kafka/Consumer/KafkaTopicMessageConsumer.cs:line 36
consumer_1   |    at Common.Kafka.Consumer.KafkaMessageConsumerManager.<>c__DisplayClass3_1.<StartConsumers>b__0() in /source/src/Common.Kafka/Consumer/KafkaMessageConsumerManager.cs:line 29
consumer_1   |    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
consumer_1   |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
consumer_1   | --- End of stack trace from previous location where exception was thrown ---
consumer_1   |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
consumer_1   |    at System.Threading.ThreadHelper.ThreadStart()
dotnet-kafka-sample_consumer_1 exited with code 139`

Seems topics are not auto generated? Or am I wrong? <-- Forget this.
Seems to be working after I Docker-Compose up for the 3rd time :)

**Comment by TopSwagCode** [comment]
By the way awesome project :) Better than all the stupid simple hello world examples out there.

**Comment by gabrielsadaka** [comment]
Sorry, I don't know why but I never received a notification for this issue and only just came across this now. I do remember having to run it twice for it to work, I don't remember the exact reason as to why that was necessary though. 

Thanks for the feedback, glad you found it useful!
